//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPlusPlus.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Blazor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Blazor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockPlusPlus.Shared.Localization.Blazor", typeof(Blazor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute this action..
        /// </summary>
        public static string ActionButtonCreateError {
            get {
                return ResourceManager.GetString("ActionButtonCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsColumnHeaderText {
            get {
                return ResourceManager.GetString("ActionsColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonChip {
            get {
                return ResourceManager.GetString("AddButtonChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Button.
        /// </summary>
        public static string AddButtonTitleThumbnail {
            get {
                return ResourceManager.GetString("AddButtonTitleThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddNewItemTitle {
            get {
                return ResourceManager.GetString("AddNewItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ApplyFilterButton {
            get {
                return ResourceManager.GetString("ApplyFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BrandAutocompleteLabel {
            get {
                return ResourceManager.GetString("BrandAutocompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BrandColumnTitle {
            get {
                return ResourceManager.GetString("BrandColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CancelConfirmText {
            get {
                return ResourceManager.GetString("CancelConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CancelDeclineText {
            get {
                return ResourceManager.GetString("CancelDeclineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, do you want to cancel?.
        /// </summary>
        public static string CancelWarningMessage {
            get {
                return ResourceManager.GetString("CancelWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string CancelWarningTitle {
            get {
                return ResourceManager.GetString("CancelWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearAllFiles {
            get {
                return ResourceManager.GetString("ClearAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearFilterButton {
            get {
                return ResourceManager.GetString("ClearFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseModalButtonTitle {
            get {
                return ResourceManager.GetString("CloseModalButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ClosePopupButtonLabel {
            get {
                return ResourceManager.GetString("ClosePopupButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CloseRevisions {
            get {
                return ResourceManager.GetString("CloseRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Columns.
        /// </summary>
        public static string ColumnChooserTitle {
            get {
                return ResourceManager.GetString("ColumnChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ColumnEditorCloseMenuButton {
            get {
                return ResourceManager.GetString("ColumnEditorCloseMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string ColumnEditorColumnHeader {
            get {
                return ResourceManager.GetString("ColumnEditorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColumnEditorResetSettingsButton {
            get {
                return ResourceManager.GetString("ColumnEditorResetSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky.
        /// </summary>
        public static string ColumnEditorStickyToggleHeader {
            get {
                return ResourceManager.GetString("ColumnEditorStickyToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string ColumnEditorVisiblityToggleHeader {
            get {
                return ResourceManager.GetString("ColumnEditorVisiblityToggleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ConfirmDefaultText {
            get {
                return ResourceManager.GetString("ConfirmDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy to clipboard.
        /// </summary>
        public static string CopyActionFail {
            get {
                return ResourceManager.GetString("CopyActionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string CopyActionSuccess {
            get {
                return ResourceManager.GetString("CopyActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButtonLabel {
            get {
                return ResourceManager.GetString("CopyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateForm {
            get {
                return ResourceManager.GetString("CreateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new {0}.
        /// </summary>
        public static string CreatingForm {
            get {
                return ResourceManager.GetString("CreatingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid Items per page.
        /// </summary>
        public static string DataGridItemPerPage {
            get {
                return ResourceManager.GetString("DataGridItemPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string DataGridItemPerPageLabel {
            get {
                return ResourceManager.GetString("DataGridItemPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid Settings.
        /// </summary>
        public static string DataGridSettings {
            get {
                return ResourceManager.GetString("DataGridSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read server data (parse error).
        /// </summary>
        public static string DataParseError {
            get {
                return ResourceManager.GetString("DataParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read server data (empty content).
        /// </summary>
        public static string DataReadEmptyError {
            get {
                return ResourceManager.GetString("DataReadEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read server data.
        /// </summary>
        public static string DataReadError {
            get {
                return ResourceManager.GetString("DataReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read server data ({0}).
        /// </summary>
        public static string DataReadStatusError {
            get {
                return ResourceManager.GetString("DataReadStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTimePickerDateLabel {
            get {
                return ResourceManager.GetString("DateTimePickerDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DateTimePickerTimeLabel {
            get {
                return ResourceManager.GetString("DateTimePickerTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string DefaultAppNotAuthorized {
            get {
                return ResourceManager.GetString("DefaultAppNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string DefaultAppNotFoundText {
            get {
                return ResourceManager.GetString("DefaultAppNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string DefaultAppNotFoundTitle {
            get {
                return ResourceManager.GetString("DefaultAppNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string DefaultAppRedirecting {
            get {
                return ResourceManager.GetString("DefaultAppRedirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAccept {
            get {
                return ResourceManager.GetString("DeleteAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeleteDecline {
            get {
                return ResourceManager.GetString("DeleteDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is deleted..
        /// </summary>
        public static string DeletedIndicator {
            get {
                return ResourceManager.GetString("DeletedIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this item?.
        /// </summary>
        public static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DeleteWarningTitle {
            get {
                return ResourceManager.GetString("DeleteWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogDefaultCancel {
            get {
                return ResourceManager.GetString("DialogDefaultCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogDefaultConfirm {
            get {
                return ResourceManager.GetString("DialogDefaultConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action on 1 item?.
        /// </summary>
        public static string DialogDefaultText {
            get {
                return ResourceManager.GetString("DialogDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action on {0} items?.
        /// </summary>
        public static string DialogDefaultTextPlural {
            get {
                return ResourceManager.GetString("DialogDefaultTextPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string DialogDefaultTitle {
            get {
                return ResourceManager.GetString("DialogDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        public static string DialogPositionBottomCenter {
            get {
                return ResourceManager.GetString("DialogPositionBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string DialogPositionBottomLeft {
            get {
                return ResourceManager.GetString("DialogPositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string DialogPositionBottomRight {
            get {
                return ResourceManager.GetString("DialogPositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string DialogPositionCenter {
            get {
                return ResourceManager.GetString("DialogPositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Left.
        /// </summary>
        public static string DialogPositionCenterLeft {
            get {
                return ResourceManager.GetString("DialogPositionCenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Right.
        /// </summary>
        public static string DialogPositionCenterRight {
            get {
                return ResourceManager.GetString("DialogPositionCenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string DialogPositionCustom {
            get {
                return ResourceManager.GetString("DialogPositionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string DialogPositionTopCenter {
            get {
                return ResourceManager.GetString("DialogPositionTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string DialogPositionTopLeft {
            get {
                return ResourceManager.GetString("DialogPositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string DialogPositionTopRight {
            get {
                return ResourceManager.GetString("DialogPositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Extra Large.
        /// </summary>
        public static string DialogSizeExtraExtraLarge {
            get {
                return ResourceManager.GetString("DialogSizeExtraExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Large.
        /// </summary>
        public static string DialogSizeExtraLarge {
            get {
                return ResourceManager.GetString("DialogSizeExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Small.
        /// </summary>
        public static string DialogSizeExtraSmall {
            get {
                return ResourceManager.GetString("DialogSizeExtraSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string DialogSizeFalse {
            get {
                return ResourceManager.GetString("DialogSizeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string DialogSizeLarge {
            get {
                return ResourceManager.GetString("DialogSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DialogSizeMedium {
            get {
                return ResourceManager.GetString("DialogSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string DialogSizeSmall {
            get {
                return ResourceManager.GetString("DialogSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string DraftColumnStateDraft {
            get {
                return ResourceManager.GetString("DraftColumnStateDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string DraftColumnStateFinal {
            get {
                return ResourceManager.GetString("DraftColumnStateFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Version.
        /// </summary>
        public static string DraftVersionCheckboxLabel {
            get {
                return ResourceManager.GetString("DraftVersionCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found, Add New.
        /// </summary>
        public static string DropdownNoItemsFound {
            get {
                return ResourceManager.GetString("DropdownNoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DropdownViewButtonText {
            get {
                return ResourceManager.GetString("DropdownViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing {0} ({1}).
        /// </summary>
        public static string EditingForm {
            get {
                return ResourceManager.GetString("EditingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as CSV.
        /// </summary>
        public static string ExportButtonTitle {
            get {
                return ResourceManager.GetString("ExportButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file.
        /// </summary>
        public static string FileUploaderError1 {
            get {
                return ResourceManager.GetString("FileUploaderError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string FileUploaderError2 {
            get {
                return ResourceManager.GetString("FileUploaderError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong: {0}.
        /// </summary>
        public static string FileUploaderError3 {
            get {
                return ResourceManager.GetString("FileUploaderError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Successfully.
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter deleted items.
        /// </summary>
        public static string FilterDeletedItemsTitle {
            get {
                return ResourceManager.GetString("FilterDeletedItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Form On Save.
        /// </summary>
        public static string FormActionCloseFormOnSave {
            get {
                return ResourceManager.GetString("FormActionCloseFormOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Form On Save.
        /// </summary>
        public static string FormActionResetFormOnSave {
            get {
                return ResourceManager.GetString("FormActionResetFormOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Form On Save.
        /// </summary>
        public static string FormActionViewFormOnSave {
            get {
                return ResourceManager.GetString("FormActionViewFormOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Close Behavior.
        /// </summary>
        public static string FormCloseBehavior {
            get {
                return ResourceManager.GetString("FormCloseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FormDefaultTitle {
            get {
                return ResourceManager.GetString("FormDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Settings.
        /// </summary>
        public static string FormSettings {
            get {
                return ResourceManager.GetString("FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string FormTaskCustom {
            get {
                return ResourceManager.GetString("FormTaskCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FormTaskDelete {
            get {
                return ResourceManager.GetString("FormTaskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not {0} the item..
        /// </summary>
        public static string FormTaskError {
            get {
                return ResourceManager.GetString("FormTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string FormTaskFetch {
            get {
                return ResourceManager.GetString("FormTaskFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Revisions.
        /// </summary>
        public static string FormTaskFetchRevisions {
            get {
                return ResourceManager.GetString("FormTaskFetchRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FormTaskNone {
            get {
                return ResourceManager.GetString("FormTaskNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string FormTaskPrint {
            get {
                return ResourceManager.GetString("FormTaskPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormTaskSave {
            get {
                return ResourceManager.GetString("FormTaskSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string GalleryDefaultTitle {
            get {
                return ResourceManager.GetString("GalleryDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string GridItemsLoadingText {
            get {
                return ResourceManager.GetString("GridItemsLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get or set column states.
        /// </summary>
        public static string HideDisabledColumnError {
            get {
                return ResourceManager.GetString("HideDisabledColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IdColumnHeaderText {
            get {
                return ResourceManager.GetString("IdColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string IdentityProfileButton {
            get {
                return ResourceManager.GetString("IdentityProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deleted.
        /// </summary>
        public static string IsDeletedColumnHeaderText {
            get {
                return ResourceManager.GetString("IsDeletedColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been Created.
        /// </summary>
        public static string ItemCreated {
            get {
                return ResourceManager.GetString("ItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been Saved.
        /// </summary>
        public static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        public static string ItemsPerPageLabel {
            get {
                return ResourceManager.GetString("ItemsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurdish.
        /// </summary>
        public static string Kurdish {
            get {
                return ResourceManager.GetString("Kurdish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListDefaultTitle {
            get {
                return ResourceManager.GetString("ListDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create language fields.
        /// </summary>
        public static string LocalizedTextFieldError {
            get {
                return ResourceManager.GetString("LocalizedTextFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file count for this form is {0}.
        /// </summary>
        public static string MaxAllowedFileUploadWarning {
            get {
                return ResourceManager.GetString("MaxAllowedFileUploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ModalClose {
            get {
                return ResourceManager.GetString("ModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ModalClose1 {
            get {
                return ResourceManager.GetString("ModalClose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Position.
        /// </summary>
        public static string ModalPosition {
            get {
                return ResourceManager.GetString("ModalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Size.
        /// </summary>
        public static string ModalSize {
            get {
                return ResourceManager.GetString("ModalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In New Tab.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files attached.
        /// </summary>
        public static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found..
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t View ({0}).
        /// </summary>
        public static string ReadAccessDenied {
            get {
                return ResourceManager.GetString("ReadAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t access ({0}).
        /// </summary>
        public static string ReadAccessDenied1 {
            get {
                return ResourceManager.GetString("ReadAccessDenied1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are viewing a revision..
        /// </summary>
        public static string RevisionIndicator {
            get {
                return ResourceManager.GetString("RevisionIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Revisions.
        /// </summary>
        public static string Revisions {
            get {
                return ResourceManager.GetString("Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Revisions.
        /// </summary>
        public static string RevisionsTitle {
            get {
                return ResourceManager.GetString("RevisionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved By.
        /// </summary>
        public static string SavedByColumnTitle {
            get {
                return ResourceManager.GetString("SavedByColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveForm {
            get {
                return ResourceManager.GetString("SaveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllButtonTitle {
            get {
                return ResourceManager.GetString("SelectAllButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectColumnHeaderText {
            get {
                return ResourceManager.GetString("SelectColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} selected.
        /// </summary>
        public static string SelectedItemsCounterLabel {
            get {
                return ResourceManager.GetString("SelectedItemsCounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse filter.
        /// </summary>
        public static string ShiftListFilterParseError {
            get {
                return ResourceManager.GetString("ShiftListFilterParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing foreign columns.
        /// </summary>
        public static string ShiftListForeignColumnError {
            get {
                return ResourceManager.GetString("ShiftListForeignColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active Only.
        /// </summary>
        public static string ShowActiveOnlyOption {
            get {
                return ResourceManager.GetString("ShowActiveOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowBothDeletedAndActiveOption {
            get {
                return ResourceManager.GetString("ShowBothDeletedAndActiveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Deleted Only.
        /// </summary>
        public static string ShowDeletedOnlyOption {
            get {
                return ResourceManager.GetString("ShowDeletedOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitTextDefault {
            get {
                return ResourceManager.GetString("SubmitTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Format.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle View.
        /// </summary>
        public static string ToggleViewMode {
            get {
                return ResourceManager.GetString("ToggleViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Failed.
        /// </summary>
        public static string UploadFailedDefaultMessage {
            get {
                return ResourceManager.GetString("UploadFailedDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading in progress....
        /// </summary>
        public static string UploadInProgress {
            get {
                return ResourceManager.GetString("UploadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFromColumnTitle {
            get {
                return ResourceManager.GetString("ValidFromColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidToColumnTitle {
            get {
                return ResourceManager.GetString("ValidToColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string ViewGalleryButton {
            get {
                return ResourceManager.GetString("ViewGalleryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing {0} ({1}).
        /// </summary>
        public static string ViewingForm {
            get {
                return ResourceManager.GetString("ViewingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewItemButtonText {
            get {
                return ResourceManager.GetString("ViewItemButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t Create/Modify ({0}).
        /// </summary>
        public static string WriteAccessDenied {
            get {
                return ResourceManager.GetString("WriteAccessDenied", resourceCulture);
            }
        }
    }
}
