//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPlusPlus.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Identity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockPlusPlus.Shared.Localization.Identity", typeof(Identity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tree.
        /// </summary>
        public static string Access_Tree {
            get {
                return ResourceManager.GetString("Access Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tree Feature is locked.
        /// </summary>
        public static string Access_Tree_Feature_is_locked {
            get {
                return ResourceManager.GetString("Access Tree Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tree List.
        /// </summary>
        public static string Access_Tree_List {
            get {
                return ResourceManager.GetString("Access Tree List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Trees.
        /// </summary>
        public static string Access_Trees {
            get {
                return ResourceManager.GetString("Access Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Tree.
        /// </summary>
        public static string Action_Tree {
            get {
                return ResourceManager.GetString("Action Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Feature is locked.
        /// </summary>
        public static string App_Feature_is_locked {
            get {
                return ResourceManager.GetString("App Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Id.
        /// </summary>
        public static string App_Id {
            get {
                return ResourceManager.GetString("App Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App List.
        /// </summary>
        public static string App_List {
            get {
                return ResourceManager.GetString("App List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to randomly assign new passwords for the selected users?.
        /// </summary>
        public static string Are_you_sure_you_want_to_randomly_assign_new_passwords_for_the_selected_users_ {
            get {
                return ResourceManager.GetString("Are you sure you want to randomly assign new passwords for the selected users?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Random Passwords.
        /// </summary>
        public static string Assign_Random_Passwords {
            get {
                return ResourceManager.GetString("Assign Random Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Access Trees contain accesses that you can not grant.
        /// </summary>
        public static string Below_Access_Trees_contain_accesses_that_you_can_not_grant {
            get {
                return ResourceManager.GetString("Below Access Trees contain accesses that you can not grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Feature is locked.
        /// </summary>
        public static string Brand_Feature_is_locked {
            get {
                return ResourceManager.GetString("Brand Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand List.
        /// </summary>
        public static string Brand_List {
            get {
                return ResourceManager.GetString("Brand List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-In Data can&apos;t be modified..
        /// </summary>
        public static string Built_In_Data_can_t_be_modified_ {
            get {
                return ResourceManager.GetString("Built-In Data can\'t be modified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password.
        /// </summary>
        public static string Choose_a_strong_password {
            get {
                return ResourceManager.GetString("Choose a strong password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Feature is locked.
        /// </summary>
        public static string City_Feature_is_locked {
            get {
                return ResourceManager.GetString("City Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City List.
        /// </summary>
        public static string City_List {
            get {
                return ResourceManager.GetString("City List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company and Region can not be changed after creation..
        /// </summary>
        public static string Company_and_Region_can_not_be_changed_after_creation_ {
            get {
                return ResourceManager.GetString("Company and Region can not be changed after creation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branch.
        /// </summary>
        public static string Company_Branch {
            get {
                return ResourceManager.GetString("Company Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branch List.
        /// </summary>
        public static string Company_Branch_List {
            get {
                return ResourceManager.GetString("Company Branch List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Feature is locked.
        /// </summary>
        public static string Company_Feature_is_locked {
            get {
                return ResourceManager.GetString("Company Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company List.
        /// </summary>
        public static string Company_List {
            get {
                return ResourceManager.GetString("Company List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        public static string Company_Type {
            get {
                return ResourceManager.GetString("Company Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is incorrect.
        /// </summary>
        public static string Current_Password_is_incorrect {
            get {
                return ResourceManager.GetString("Current Password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Feature is locked.
        /// </summary>
        public static string Department_Feature_is_locked {
            get {
                return ResourceManager.GetString("Department Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        public static string Department_List {
            get {
                return ResourceManager.GetString("Department List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Display_Name {
            get {
                return ResourceManager.GetString("Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required.
        /// </summary>
        public static string Display_Name_is_required {
            get {
                return ResourceManager.GetString("Display Name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate users are not allowed..
        /// </summary>
        public static string Duplicate_users_are_not_allowed_ {
            get {
                return ResourceManager.GetString("Duplicate users are not allowed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification link sent successfully..
        /// </summary>
        public static string Email_verification_link_sent_successfully_ {
            get {
                return ResourceManager.GetString("Email verification link sent successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate auth-code.
        /// </summary>
        public static string Failed_to_genearate_auth_code {
            get {
                return ResourceManager.GetString("Failed to genearate auth-code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate the token.
        /// </summary>
        public static string Failed_to_genearate_token {
            get {
                return ResourceManager.GetString("Failed to genearate token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot Password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ Address.
        /// </summary>
        public static string HQ_Address {
            get {
                return ResourceManager.GetString("HQ Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ Email.
        /// </summary>
        public static string HQ_Email {
            get {
                return ResourceManager.GetString("HQ Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ Phone.
        /// </summary>
        public static string HQ_Phone {
            get {
                return ResourceManager.GetString("HQ Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration ID.
        /// </summary>
        public static string Integration_ID {
            get {
                return ResourceManager.GetString("Integration ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string Invalid_Phone_Number {
            get {
                return ResourceManager.GetString("Invalid Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string Invalid_refresh_token {
            get {
                return ResourceManager.GetString("Invalid refresh token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        public static string Last_Seen {
            get {
                return ResourceManager.GetString("Last Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string Legal_Name {
            get {
                return ResourceManager.GetString("Legal Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password can not be the same as the current password.
        /// </summary>
        public static string New_Password_can_not_be_the_same_as_the_current_password {
            get {
                return ResourceManager.GetString("New Password can not be the same as the current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items found..
        /// </summary>
        public static string No_Items_found_ {
            get {
                return ResourceManager.GetString("No Items found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be empty..
        /// </summary>
        public static string Password_can_not_be_empty_ {
            get {
                return ResourceManager.GetString("Password can not be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URI.
        /// </summary>
        public static string Redirect_Uri {
            get {
                return ResourceManager.GetString("Redirect Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region List.
        /// </summary>
        public static string Region_List {
            get {
                return ResourceManager.GetString("Region List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link has been sent to your email..
        /// </summary>
        public static string Reset_password_link_has_been_sent_to_your_email_ {
            get {
                return ResourceManager.GetString("Reset password link has been sent to your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send login info to the user.
        /// </summary>
        public static string Send_login_info_to_the_user {
            get {
                return ResourceManager.GetString("Send login info to the user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Password Link.
        /// </summary>
        public static string Send_Reset_Password_Link {
            get {
                return ResourceManager.GetString("Send Reset Password Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Feature is locked.
        /// </summary>
        public static string Service_Feature_is_locked {
            get {
                return ResourceManager.GetString("Service Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service List.
        /// </summary>
        public static string Service_List {
            get {
                return ResourceManager.GetString("Service List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Code.
        /// </summary>
        public static string Short_Code {
            get {
                return ResourceManager.GetString("Short Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Phone.
        /// </summary>
        public static string Short_Phone {
            get {
                return ResourceManager.GetString("Short Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Working Day.
        /// </summary>
        public static string Standard_Working_Day {
            get {
                return ResourceManager.GetString("Standard Working Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Working Hours.
        /// </summary>
        public static string Standard_Working_Hours {
            get {
                return ResourceManager.GetString("Standard Working Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Feature is locked.
        /// </summary>
        public static string Team_Feature_is_locked {
            get {
                return ResourceManager.GetString("Team Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team List.
        /// </summary>
        public static string Team_List {
            get {
                return ResourceManager.GetString("Team List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string Team_Name {
            get {
                return ResourceManager.GetString("Team Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the access tree name {0} already exists..
        /// </summary>
        public static string the_access_tree_name__0__already_exists_ {
            get {
                return ResourceManager.GetString("the access tree name {0} already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App ID {0} already exists..
        /// </summary>
        public static string The_App_ID__0__already_exists_ {
            get {
                return ResourceManager.GetString("The App ID {0} already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app &lt;b&gt;&apos;{0}&apos;&lt;/b&gt; is trying to access your account.
        /// </summary>
        public static string The_app_is_trying_to_access_your_account {
            get {
                return ResourceManager.GetString("The app is trying to access your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email {0} exist.
        /// </summary>
        public static string The_email__0__exist {
            get {
                return ResourceManager.GetString("The email {0} exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone {0} exist.
        /// </summary>
        public static string The_phone__0__exist {
            get {
                return ResourceManager.GetString("The phone {0} exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is deactivated.
        /// </summary>
        public static string The_user_is_deactivated {
            get {
                return ResourceManager.GetString("The user is deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user will be redirected to.
        /// </summary>
        public static string The_user_will_be_redirected_to {
            get {
                return ResourceManager.GetString("The user will be redirected to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username {0} exist.
        /// </summary>
        public static string The_username__0__exist {
            get {
                return ResourceManager.GetString("The username {0} exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is verified.
        /// </summary>
        public static string This_email_address_is_verified {
            get {
                return ResourceManager.GetString("This email address is verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is verified.
        /// </summary>
        public static string This_phone_number_is_verified {
            get {
                return ResourceManager.GetString("This phone number is verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Feature is locked.
        /// </summary>
        public static string User_Feature_is_locked {
            get {
                return ResourceManager.GetString("User Feature is locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked down for {0} minutes.
        /// </summary>
        public static string User_is_lockdown_for__0__minutes {
            get {
                return ResourceManager.GetString("User is lockdown for {0} minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string Username_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("Username or password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Emails.
        /// </summary>
        public static string Verify_Emails {
            get {
                return ResourceManager.GetString("Verify Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phones.
        /// </summary>
        public static string Verify_Phones {
            get {
                return ResourceManager.GetString("Verify Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reseted successfully.
        /// </summary>
        public static string Your_password_reseted_successfully {
            get {
                return ResourceManager.GetString("Your password reseted successfully", resourceCulture);
            }
        }
    }
}
