@rootUrl=http://localhost:5069/api
@IsHardDelete = true
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjVSWDJFIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlN1cGVyVXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IlN1cGVyIFVzZXIiLCJTaGlmdFNvZnR3YXJlL1NoaWZ0RW50aXR5L0NsYWltcy9SZWdpb25JZCI6Im9hWDRhIiwiU2hpZnRTb2Z0d2FyZS9TaGlmdEVudGl0eS9DbGFpbXMvQ29tcGFueUlkIjoiTjJyTFIiLCJTaGlmdFNvZnR3YXJlL1NoaWZ0RW50aXR5L0NsYWltcy9Db21wYW55QnJhbmNoSWQiOiJHeHZ5SyIsIkV4dGVybmFsVG9rZW4iOiJmYWxzZSIsIlNoaWZ0U29mdHdhcmUvVHlwZUF1dGgvQ2xhaW1zL0FjY2Vzc1RyZWUiOiJ7XCJTaGlmdElkZW50aXR5QWN0aW9uc1wiOlsxLDIsMyw0XSxcIlN5c3RlbUFjdGlvblRyZWVzXCI6WzEsMiwzLDRdLFwiU3RvY2tBY3Rpb25UcmVlc1wiOlsxLDIsMyw0XX0iLCJleHAiOjE3MDIzNjY4NzMsImlzcyI6IlN0b2NrUGx1c1BsdXMifQ.mTuoftVeMG1Wv3V751rOWVCmMHisXYqyqs8zdAWN5AeXuoyXHhi4tKTXzezDue6ROi3kniFp_42dtJDXB6IaEA
@id=35

DELETE {{rootUrl}}/IdentityService/{{id}}?IsHardDelete={{IsHardDelete}}
Authorization: Bearer {{token}}